### ISSUE TITLE
FrankerFaceZ Emotes (sizing)

### ISSUE THREAD

**Issue by D3thw0lf** [TheUnlocked/Better-Mixer#12]
Seems like the sizing is a bit broken (only FFZ Emotes)
![sizing_broken](https://user-images.githubusercontent.com/895448/44555226-76ea3a80-a734-11e8-81ad-c5256adee580.png)

**Comment by D3thw0lf** [comment]
I would also find it helpful if they get seperated a bit for example all BTTV in one row/tab whatever thing and all FFZ in their own row/tab thing whatever ^^ (just a suggestion like in #10 )

**Comment by TheUnlocked** [comment]
I think I patched this bug, but I may not have pushed that update to the webstore. I'll make sure it's fixed on my end and then push the update.

**Comment by D3thw0lf** [comment]
got it ^^' ... hope it's ok to create that PR (tested on my local machine and worked)

**Comment by TheUnlocked** [comment]
The update should show up on the webstore within the hour and it should be pushed to users' computers within a few hours.

**Comment by D3thw0lf** [comment]
Thanks again for fast fixing this issue. Can't wait to see what's coming next. ^w^
