### ISSUE TITLE
⚙️Feature-Request: Autoselect Filter-Option (language)

### ISSUE THREAD

**Issue by D3thw0lf** [TheUnlocked/Better-Mixer#16]
Heyho what do you think about an "auto choose selected language"-Feature?

What I mean by that is if you click, for example, on the "popular streams" page, you have to choose your desired language (for example, German, Spanish, English, etc.) again and again. It would be great to have some sort of autoselect my "default" language on the filter with the "?languageId="-Tag in the URL.

Example:
https://mixer.com/browse/all?languageId=en
https://mixer.com/browse/all?languageId=de
https://mixer.com/browse/all?languageId=es
etc.

I know this could be a bigger "thing" todo but I guess this would be extrem helpful to find first what you're looking for (in your choosed language) and a cool addition to make mixer a bit better (again) ^^'

Let me know what you think. :D

**Comment by D3thw0lf** [comment]
List of all available Filter-Languages (if needed)

- ar
- da
- de
- en
- fi
- fr
- he
- it
- ja
- zh-hk
- ko
- zh
- nl
- nb
- pl
- pt
- ru
- sv
- es
- tr

**Comment by TheUnlocked** [comment]
I'll look into it.

**Comment by TheUnlocked** [comment]
I implemented a "Save Filters" button in 2.0.4 (#17) which covers this feature in a more general sense. I probably won't push it to the webstore quite yet, but if you're loading the extension from source you can use that new feature.

**Comment by D3thw0lf** [comment]
nice, thanks ^w^
