### ISSUE TITLE
Autoselect Filter-Option (language) enhancement

### ISSUE THREAD

**Issue by D3thw0lf** [TheUnlocked/Better-Mixer#22]
related #16 

Just a quick issue thing:
Would be great if you could add the saving of language to "up-and-coming", too. 👍 
https://mixer.com/browse/up_and_coming

as always... keep up the great work ❤️

**Comment by TheUnlocked** [comment]
I'll look into it soon.

**Comment by D3thw0lf** [comment]
Ah nice. Thanks for the fast answer. :O

**Comment by TheUnlocked** [comment]
Added a general solution in 2cb080f349b61d5ff079064d87c6db7df5bcfe6e. The update should be pushed to users soon.
