### ISSUE TITLE
Embers Button

### ISSUE THREAD

**Issue by mtcdood** [TheUnlocked/Better-Mixer#29]
Mixer has added a button to buy embers and on narrow screens it pushes the level, username, sparks, and avatar off the screen. Maybe Better Mixer can fix it.

![image of page](https://my.mixtape.moe/cldfmz.png)

Note that when the screen gets even narrower the layout changes and the issue goes away.

**Comment by TheUnlocked** [comment]
I'll look into it.

**Comment by TheUnlocked** [comment]
It turns out that this isn't actually an issue caused by the embers button, the button just makes it appear for a wider range of window widths. Any solution would have to substantially change how the top bar works, which I won't do for now.

**Comment by TheUnlocked** [comment]
Mixer has fixed this natively.
