### ISSUE TITLE
Feature-Idea - Toggle "resizing" of Chat

### ISSUE THREAD

**Issue by D3thw0lf** [TheUnlocked/Better-Mixer#30]
![image](https://user-images.githubusercontent.com/895448/55872275-e1010400-5b8c-11e9-9223-331d67947251.png)
Would be great if it's possible to add a switch to enable/disable resizing of chat. Sometimes I accidentally moving the chat in size and this would simply fix this if resizing is toggleable. :D 

And ofc as always thanks for your hard work on this <3

**Comment by TheUnlocked** [comment]
Great idea. Committed in 4aa9c90c3790cd7fca4dad2ee07595532ee44a4d and will push to the webstore soon.
