### ISSUE TITLE
Notifications Show Odd Messages

### ISSUE THREAD

**Issue by mtcdood** [TheUnlocked/Better-Mixer#32]
![image](https://user-images.githubusercontent.com/42127748/59156092-335e8400-8a5b-11e9-81c0-4aa9f23f8aea.png)
This should say "8 days ago" or "Jun 1", not "Jun 1 ago." Mixer has never fixed it.

**Comment by TheUnlocked** [comment]
This could be an interesting one to fix... it's obviously not critical, but I might take it on anyways. Thanks for pointing this out.

**Comment by TheUnlocked** [comment]
Fixed in 4aa95696b60bf2d889a9c92ef5e91c5e59a291b8
