### ISSUE TITLE
Excessive Memory Usage

### ISSUE THREAD

**Issue by mtcdood** [TheUnlocked/Better-Mixer#33]
With Better Mixer enabled I get memory usage like this after a few hours:
![image](https://user-images.githubusercontent.com/42127748/59493994-d3e4e780-8e51-11e9-934e-9f7a08fb5bdc.png)

Without it the memory usage caps at about 1/10th.

**Comment by TheUnlocked** [comment]
That's very odd. I'll look into it.

**Comment by TheUnlocked** [comment]
Are those hours sitting idle with the tab open in the background or are they active watching?

**Comment by mtcdood** [comment]
I leave the tab open while they stream pretty much 24/7/365.

**Comment by TheUnlocked** [comment]
Meaning that a stream is playing in the background when the memory usage gets very high?

**Comment by mtcdood** [comment]
Yeah.

**Comment by TheUnlocked** [comment]
Chat contents aren't stored by Better Mixer and nothing should be preventing garbage collection from taking place on data allocated for message processing. I'm going to run some more tests.

**Comment by TheUnlocked** [comment]
After ~3 hour tests with and without the extension, I can't seem to reproduce this issue. I'll try to look a bit further into potential causes, but without a reproduction on my side there's not a whole lot I'm able to do.

**Comment by mtcdood** [comment]
I also set the player to 160p and mute it. I don't know if that will affect anything.

**Comment by TheUnlocked** [comment]
@mtcdood I disabled a currently unused feature which could have resulted in a memory explosion in dfab1ea48cc3ece60fc46678606fd063a9b31274. I'll push it to the webstore soon. LMK if it changes anything.
