### ISSUE TITLE
Disable automatically playing VODs when loading an offline channel page on Mixer.

### ISSUE THREAD

**Issue by CedarD** [TheUnlocked/Better-Mixer#34]
As the title suggests...would it be possible to make it so that when we load an offline channel's Mixer page it doesn't automatically start playing some previous broadcast? (Don't know if Mixer settings allow this natively, but I couldn't find it.)

**Comment by TheUnlocked** [comment]
I'd love this too but I don't know if it's actually possible. It may be more viable to just pause the VOD when it loads, but I'm not sure that I can actually stop the VOD from appearing altogether.

**Comment by CedarD** [comment]
While not as good as removing the VOD via script, if that's not possible, then automatically pausing it would be waaaay better than it playing. It's just annoying to have to pause it every time I load a page.

**Comment by TheUnlocked** [comment]
Resolved in 8d6c08d3a187e8cdbdf97aabdb6ce8a04b18b045. The solution is not ideal, but it generally produces the desired effect. Combined with #5 being resolved, this should be pretty good.
