### ISSUE TITLE
Globals and BTTV

### ISSUE THREAD

**Issue by mtcdood** [TheUnlocked/Better-Mixer#4]
Would you accept a pull request for Twitch global, FrankerFaceZ global, and BTTV global + channel support as well?

**Comment by TheUnlocked** [comment]
I would not accept a PR for globals. However, if you want to implement something for BTTV channel support, I'd probably accept that.

**Comment by mtcdood** [comment]
People can install the Global Twitch emotes addon if they want to use globals, which is a second choice for those. The synchronization and menu of this addon are definitely reasons to use this for channel-specific emotes.

**Comment by mtcdood** [comment]
This is an example of the API for BetterTwitchTV emotes: https://api.betterttv.net/2/channels/mtcdood

I'll take a look at this later.

**Comment by mtcdood** [comment]
[Here](https://github.com/mtcdood/Better-Mixer/commit/6ff52b0fea80ba269fcefe841432b37d79a0471a) is a skeleton that probably gets the BTTV API's JSON correctly.

**Comment by TheUnlocked** [comment]
Thanks. I'm writing the surrounding code to properly merge it.

**Comment by TheUnlocked** [comment]
Alright, it has been integrated and merged. It will be pushed to the chrome webstore after I'm pretty sure everything is fully stable.

**Comment by mtcdood** [comment]
Global Twitch, FFZ, and BTTV json:
- https://twitchemotes.com/api_cache/v3/global.json : 197 emotes
- https://api.frankerfacez.com/v1/set/global : 101 emotes
- https://api.frankerfacez.com/v1/set/global : 42 emotes
