### ISSUE TITLE
Better Mixer's requests to FFZ/BTTV conflict with Brave shield

### ISSUE THREAD

**Issue by TheUnlocked** [TheUnlocked/Better-Mixer#57]
Reported by @qome

Question: Does the emote menu load properly if you disable MixrElixr?

**Comment by qome** [comment]
Not always. I hadn't thought to check. Have you tried Brave? That's the only browser I can reproduce it on.

**Comment by TheUnlocked** [comment]
It seems to be an issue with Brave's "shield" blocking requests to FFZ/BTTV. I don't know enough about how Brave works to fix this, or even to know if I can fix this. I'll leave this up in case anyone with better knowledge of this comes along, but for now it's getting wontfix.

**Comment by qome** [comment]
Wouldn't that make it never work, instead of sometimes work?

**Comment by TheUnlocked** [comment]
I'm not sure how Brave's tech works, so I couldn't say. However, upon disabling the feature, Better Mixer works fine for me.

**Comment by TheUnlocked** [comment]
I believe this is now fixed. I have no idea what caused it to no longer be an issue.
