### ISSUE TITLE
BTTV emotes not appearing in Firefox

### ISSUE THREAD

**Issue by delet-1** [TheUnlocked/Better-Mixer#58]
I'm using the latest version from the Firefox store version 3.1.4

**Comment by TheUnlocked** [comment]
It looks like Twitch made a change to their API that makes client-side use of it nigh-impossible without making every single user authenticate. I'll try to weigh solutions to this and come up with a fix as soon as possible.

**Comment by TheUnlocked** [comment]
This has been fixed in 5458932ce838c1f56592da319d2aaf855da0f9f7.
